In [1]:
import math
import numpy as np
from numpy import linalg
import torch
from torch import tensor
from torch.autograd.functional import jacobian, hessian
pi=math.pi

In [2]:
# takes in tensors
BraninHoo = lambda x: (x[...,1] - (5.1*x[...,0]**2/4/pi/pi) +(5*x[...,0]/pi)-6)**2 + (10-10/8/pi)*torch.cos(x[...,0])+10
rosenbrock = lambda x: 100*(x[...,1] - x[...,0]**2)**2 + (x[...,0]-1)**2

# accepts tensor and int
def Branin(x0,x1):
    return (x1 - (5.1*x0**2/4/pi/pi) +(5*x0/pi)-6)**2 + (10-10/8/pi)*np.cos(x0)+10

def rosen(x0,x1):
    return 100*(x1 - x0**2)**2 + (x0-1)**2



In [35]:
round(100/2.3)


43

In [29]:
def backtrack(x,fun,grad, pk,a, type="firstwolfe"):
    # computations: grad, functionx2
    
    c1=.3
    c2=.75
    rho=.9
    grad_dot_pk=torch.dot(grad,pk)
    iter=0
    if type == "firstwolfe":
        while fun(x+a*pk)>=fun(x)+c1*a*grad_dot_pk: # first wolfe
            a*=rho
            iter+=1
            if iter%20=0:
                a=
            if iter>100:
                break
            """
            print('first alpha')
            print(a)
            print(f'function{fun(x+a*pk)}')
            print(f'function next: {fun(x)+c1*a*grad_dot_pk}')
            """
            
            
        
    elif type == "fullwolfe":
        while fun(x+a*pk)>=fun(x)+c1*a*grad_dot_pk: # first wolfe
            a*=rho
            #print('first alpha')
            #print(a)
            iter+=1
            if iter>20:
                break
        iter=0
        while torch.dot(jacobian(fun, x+a*pk), pk) <= c2*grad_dot_pk:
            a/=rho
            #print('second alpha')
            #print(a)
            iter+=1
            if iter>20:
                break
                
    elif type == "strongwolfe":
        while fun(x+a*pk)>=fun(x)+c1*a*grad_dot_pk: # first wolfe
            a*=rho
            iter+=1
            if iter>20:
                break
        iter=0
        while torch.dot(jacobian(fun, x+a*pk), pk) <= c2*grad_dot_pk:
            a/=rho
            #print("full in strong wolfe")
            iter+=1
            if iter>20:
                break
        iter=0
        while abs(torch.dot(jacobian(fun, x+a*pk), pk)) >= abs(c2*grad_dot_pk):
            a*=rho
            #print("strong in strong wolfe")
            iter+=1
            if iter>20:
                break
                
    elif type == "interpolation":
        while fun(x+a*pk)>=fun(x)+c1*a*grad_dot_pk: # first wolfe
            alpha = (-grad*a**2)/(fun(a-fun(x)-a*grad))
    else:
        print("wrong criteria type")

    return a


In [30]:
# FIRST ORDER LINE SEARCH
## 1 - first order line search
"""
find search direction using gradient
find alpha step length using 3 different methods
1. first wolfe
2. full wolfe
3. strong wolfe
4. quadratic interpolation
"""
stop=0.0001
def line_search(x_0, f, stop,a, type="firstwolfe"):
    iter=0
    x = torch.tensor(x_0, dtype=torch.float32)
    grad_norm=10
    
    while grad_norm>stop:
        grad = jacobian(f,x)
        grad_norm=torch.norm(grad)
        
        #grad = grad.numpy(), to nparray
        pk = -grad/grad_norm
        a = backtrack(x, f,grad,pk,a, type)
        #print(pk,a)
        x=x+pk*a
        iter+=1
        if iter%500==0:
            print(iter, a)
            print(iter, grad)
            print(iter, grad_norm)
    print(iter)
    print(f'minimizer: {x}')
    print(f'function value: {f(x)}')
        
line_search([6,10], BraninHoo, stop,1)
line_search([6,10], BraninHoo, stop,1, "fullwolfe")
line_search([6,10], BraninHoo, stop,1, "strongwolfe")

500 2.5e-323
500 tensor([-0.0001,  0.0010])
500 tensor(0.0010)
1000 2.5e-323
1000 tensor([-0.0001,  0.0010])
1000 tensor(0.0010)
1500 2.5e-323
1500 tensor([-0.0001,  0.0010])
1500 tensor(0.0010)
2000 2.5e-323
2000 tensor([-0.0001,  0.0010])
2000 tensor(0.0010)
2500 2.5e-323
2500 tensor([-0.0001,  0.0010])
2500 tensor(0.0010)
3000 2.5e-323
3000 tensor([-0.0001,  0.0010])
3000 tensor(0.0010)


KeyboardInterrupt: 

In [3]:
# plan of attack
# 1 - search direction
# 2 - find steplength

## for each method 
# report gradiant and step length at each iteration and plot
#report ; minimizer, minimum, # of function and gradient evaluation, & interpret results

## 1 - first order line search
"""
find search direction using gradient
find alpha step length using 3 different methods
1. first wolfe
2. full wolfe
3. strong wolfe
4. quadratic interpolation
"""

## 2 - newton and quasi newton
"""
find newton search direction 
    and quasi newton 
find alpha step length using strong wolfe
"""

## 3 - trust region
"""
first order taylor appr, alpha is edge of trust region
second order taylor appr, alpha is min of mk
"""

"""
functions needed:
* backtrack(x,function, search direction, criteria) return alpha
* search direction (function, type) return search direction
* trust region (region size, x, function, type) return next point
* taylor approximation
* along the way save norm of gradient and alpha
* at the end show minimizer, minumum, and # of function and gradient evalution
"""





'\nfunctions needed:\n* backtrack(x,function, search direction, criteria) return alpha\n* search direction (function, type) return search direction\n* trust region (region size, x, function, type) return next point\n* taylor approximation\n* along the way save norm of gradient and alpha\n* at the end show minimizer, minumum, and # of function and gradient evalution\n'

In [4]:
gradient_stop = 0.00001


def PK(f,x, type="steepest_descent"):
    # steepest descent
    # newton
    # quasi newton
    grad = jacobian(f,x)
    if type == "steepest_descent":
        
        pk=-grad/norm(grad)
        
    elif type =="newton":
        
        hess = hessian(f,x)
        pk= - torch.dot(inv(hess),grad)
    elif type == "quasi_newton":
        #yk = grad(k+1)-grad(k)
        #sk = x(k+1)-x(k)
        yk = grad
        sk = 
        Hk = Hk - 
        pk= - torch.dot(Bk_inv,grad)
        
    else:print("wrong type for search direction")
    
    return pk

def trust_region(x, f, region_size, type="1st"):
    # define a grid of circular point around x
    
    grad = jacobian(f,x)
    f(x)+tensor.dot(
    if type =="1st":
        
    elif type == "2nd":
        hess = hessian(f,x)
        
    else: print("wrong type")
    
    n1=.25
    n2=.75
    
    return next_x

SyntaxError: invalid syntax (1385914922.py, line 52)

In [82]:
x=torch.tensor([[1,2],[3,4]])
y=torch.tensor([[[3,2],[5,6]],[[1,2],[3,4]]])
#print(x)
#print(y)


xy=x*y
print(xy)
print(xy[0])
print(torch.sum(xy,1))
print(torch.sum(xy,2))

print(torch.sum(xy,[1,2]))
print(torch.sum(xy,[2,1]))
#print(sum(sum(x*y)))

# look into numpy
# leave trust region last 
# incorporate results publish

tensor([[[ 3,  4],
         [15, 24]],

        [[ 1,  4],
         [ 9, 16]]])
tensor([[ 3,  4],
        [15, 24]])
tensor([[18, 28],
        [10, 20]])
tensor([[ 7, 39],
        [ 5, 25]])
tensor([46, 30])
tensor([46, 30])


In [ ]:
x=torch.tensor([1,2])
r=3
grid=.1
